
version: 2

models:
    - name: stage_customers
      description: "Contains information to the customers."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stage_orders
      description: "Contains information to all shipped orders."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: stage_subscriptions
      description: "Contains sub- & unsub- scription dates per customer to the subscription model."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: mart_cohorts
      description: "The dimension of the table is based on the cohorts and all metrics for each point in time (action months). "
      columns:
          - name: cohort_month
            description: "The month of cohort creation"
          - name: action_month
            description: "The month of an action happening (e.g. order placed, customer subscribed)"

            
